version: 0.0
os: linux
files:
  - source: /themes/be
    destination: /var/www/html/wp-content/themes/be
  - source: /plugins
    destination: /var/www/html/wp-content/plugins
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
