version: '3'

services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    volumes:
      - ./.sql:/docker-entrypoint-initdb.d:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    platform: linux/x86_64

  web:
    env_file:
      - .env
    depends_on:
      - db
    image: wordpress:${WP_IMAGE_VERSION}
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./vendor:/var/www/vendor
      - ./.wp:/var/www/html
      - ./.env:/var/www/.env
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./.htaccess:/var/www/html/.htaccess
